services:
  sonar:
    image: sonarqube:25.11.0.114957-community
    depends_on:
      - db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_EXTERNALURL=http://enlightenedly-figurate-chadwick.ngrok-free.dev
    volumes:
      - ./data/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube_logs:/opt/sonarqube/logs
      - ./data/sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    networks:
      - sonar

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar

networks:
  sonar:
